### ISSUE TITLE
French Translation Progress

### ISSUE THREAD

**Issue by gatsbybot** [gatsbyjs/gatsby-fr#1]
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, please read the [translation guide](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#contributing-to-a-translation) to understand the Gatsby translation process.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

- [ ] Home Page (@gatsbybot) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

**These pages should be translated first.** These pages must be translated to be considered an official Gatsby localization.

### Community

* [x] community/code-of-conduct (@dantereve) #2 
    

### Tutorial

* [x] tutorial/index (@dantereve) #3 
* [x] tutorial/part-zero (@alexislepresle) #22
* [x] tutorial/part-one (@SamuelAlev) #11 
* [x] tutorial/part-two (@dantereve) #8 
* [x] tutorial/part-three (@dantereve) #12 
* [x] tutorial/part-four (@SamuelAlev) #14 
* [x] tutorial/part-five (@dantereve) #19 
* [x] tutorial/part-six (@MustaphaLimam) #13
* [ ] tutorial/part-seven  (@rnd-debug) #64 
* [x] tutorial/part-eight (@Marie-Carrere) #43
* [x] tutorial/themes-tutorials (@mindsers) #23 
    
### Docs

* [x] docs/index (@mindsers) #7 
* [x] docs/quick-start (@benoitcalin) #21 
* [ ] docs/glossary (@dantereve)
* [x] docs/gatsby-cli (@MustaphaLimam) #15 
* [x] docs/accessibility-statement (@mindsers) #37 

#### Recipes

* [x] docs/recipes (@benoitcalin) #16 
* [ ] docs/recipes/pages-layouts (@MustaphaLimam)
* [x] docs/recipes/styling-css (@brainlulz) #36 
* [x] docs/recipes/working-with-starters (@brainlulz) #40 
* [x] docs/recipes/working-with-themes (@Marie-Carrere) #44
* [x] docs/recipes/sourcing-data (@brainlulz) #45 
* [ ] docs/recipes/querying-data (@rnd-debug) #63 
* [ ] docs/recipes/working-with-images (@tithi1march) #72 
* [x] docs/recipes/transforming-data (@Marie-Carrere) #46
* [x] docs/recipes/deploying-your-site

#### API Reference

* [x] docs/api-reference (@noisefilter19) #35
* [ ] docs/theme-api (@akashamin01) #75
* [x] docs/gatsby-link (@rnd-debug) #69 
* [ ] docs/gatsby-image (@akashpatel1310) #76 
* [ ] docs/gatsby-config (@jelonmusk)
* [x] docs/browser-apis (@Prabhu646) #38
* [x] docs/ssr-apis (@Marie-Carrere) #47
* [x] docs/api-files (@Marie-Carrere) #65 
* [x] docs/api-files-gatsby-config (@gauravgupta45) #51
* [x]  docs/api-files-gatsby-browser (@gauravgupta45) #53
* [x]  docs/api-files-gatsby-node (@noisefilter19) #54
* [x]  docs/api-files-gatsby-ssr (@noisefilter19) #56 
* [x] docs/actions (@gauravgupta45) #48 
* [x] docs/graphql-api (@gauravgupta45) #61 
* [x] docs/node-apis (@gauravgupta45) #49 
* [ ] docs/node-api-helpers (@Marie-Carrere)
* [x] docs/node-model (@gauravgupta45) #50 
* [ ] docs/node-interface (@Marie-Carrere)
* [ ] docs/schema-customization (@grimm989)
* [ ] docs/api-specification (@Lavish-Garg) #59 
  
### Contributing

* [x] contributing/index (@mindsers) #39
* [ ] contributing/community-contributions (@prateekpardeshi)
* [x] contributing/contributor-swag (@SamuelAlev) #27
* [x] contributing/how-to-contribute (@prateekpardeshi) #26

**Comment by dantereve** [comment]
I'm going to start with contributing/code-of-conduct.

**Comment by dantereve** [comment]
code of conduct ok, I'll go for tutorial/index now.

**Comment by alexislepresle** [comment]
I'll start working on tutorial/part-zero (I translated half)

**Comment by SamuelAlev** [comment]
I'll start working on tutorial/part-one

**Comment by mindsers** [comment]
I'm gonna start with docs/index

**Comment by nclsppr** [comment]
Hi, I saw that docs/quick-start was free so I did it in PR #4

**Comment by dantereve** [comment]
tutorial/part-two, here I am!

**Comment by SandipPalit** [comment]
I am going to translate docs/glossary

**Comment by dantereve** [comment]
I'm moving on tutorial/part-three

**Comment by SamuelAlev** [comment]
I'm gonna start tutorial/part-four

**Comment by dantereve** [comment]
Next : tutorial/part-five for me

**Comment by MustaphaLimam** [comment]
Hi can I start by translating tutorial/part-six ?

**Comment by SamuelAlev** [comment]
@MustaphaLimam Yes, your help will be welcome 😄

**Comment by dantereve** [comment]
@MustaphaLimam, If you need anything don't hesitate to reach out to us on Discord

**Comment by MustaphaLimam** [comment]
Thanks for your attention everyone ! So I did a PR for tutorial/part-six. Happy to help out on this translation !

**Comment by sheplu** [comment]
Hello ! I would like to help on this project to translate gatsby. I will have some time dedicated to that.
In the past and current month I was / am helping translate the Reactjs documentation. I should land a PR today :)

edit: I will take `tutorial/part-seven`

**Comment by SamuelAlev** [comment]
Hello 👋
Your help is greatly appreciated !
If you have any questions, feel free to reach us on Discord (#translation-fr).

**Comment by MustaphaLimam** [comment]
Hi ! I will take docs/gatsby-cli

**Comment by SamuelAlev** [comment]
I'll take tutorial/part-eight

**Comment by benoitcalin** [comment]
Hi guys, I will work on docs/recipes if it’s ok for you all :)

**Comment by SamuelAlev** [comment]
Hello @benoitcalin :wave: 
Happy to have you here, of course you can participate !
I'll add you on docs/recipes so.

**Comment by SamuelAlev** [comment]
Hello @benoitcalin :wave: 
Happy to have you here, of course you can participate !
I'll add you on docs/recipes so.

**Comment by dantereve** [comment]
I'm taking docs/glossary. Let's keep this moving. 🎄

**Comment by benoitcalin** [comment]
I guys, I could find some time to do quick-start, is it only the quick-start.md file ?

**Comment by mindsers** [comment]
@benoitcalin It should be, yes

**Comment by gaurav-ag10** [comment]
can I take docs/quick-start.md ?

**Comment by SamuelAlev** [comment]
Hi @gaurav-ag10 !
It's already taken (#21), sorry 
Check the others files that aren't already translated :)

**Comment by the-coder-dude** [comment]
@SamuelAlev Can I take `docs/contributing/how-to-contribute.md` ?  🙂

**Comment by SamuelAlev** [comment]
Hi @prateekpardeshi 👋
Of course!
I linked you to the file, you can start to translate when you want :)

**Comment by the-coder-dude** [comment]
Hello @SamuelAlev, Done translation `docs/contributing/how-to-contribute.md` PR #26 

Please have a look! Suggestions are welcome 🙂

**Comment by the-coder-dude** [comment]
@SamuelAlev Can I take `docs/contributing/community-contributions.md` ?

**Comment by mindsers** [comment]
@prateekpardeshi Of course!

**Comment by Marie-Carrere** [comment]
Hi ! 😀

I would like to contribue and take the `tutorial/part-eight`
Let me know if this part is still available.

Thanks

**Comment by SamuelAlev** [comment]
Hi @Marie-Carrere 👋 
Thank you for your interest in Gatsby !
The part still available so you can take it.

**Comment by Marie-Carrere** [comment]
Awesome ! 😁
I just started to work on the `tutorial/part-eight`

**Comment by noisefilter19** [comment]
Hello!
Can i work on  docs/api-reference
Submitted PR #35

**Comment by MustaphaLimam** [comment]
Hi ! Can I take docs/recipes/pages-layouts ?

**Comment by MustaphaLimam** [comment]
Hi ! I will take docs/recipes/pages-layouts

**Comment by k0mpreni** [comment]
Hi! I will take docs/recipes/styling-css

**Comment by mindsers** [comment]
Welcome to all the new contributors! Thanks for your interest and your work! 🎉 🚀

**Comment by Prabhu646** [comment]
Hi. I'm new to Github. I will take up docs/browser-apis

**Comment by k0mpreni** [comment]
Hi, I will take "docs/recipes/working-with-starters"

**Comment by Marie-Carrere** [comment]
Hi guys ! 😀
I would like to take the part about `docs/recipes/working-with-themes`

**Comment by k0mpreni** [comment]
Hello, I will take `docs/recipes/sourcing-data` :)

**Comment by gauravgupta45** [comment]
Hi! I'll be taking `docs/action`. #48

**Comment by gauravgupta45** [comment]
Going with `docs/node-apis` now. #49

**Comment by gauravgupta45** [comment]
Moving on to `docs/node-model.md`.

**Comment by gauravgupta45** [comment]
Gonna go with `docs/api-files-gatsby-config` if that's fine.

**Comment by gauravgupta45** [comment]
Working on `docs/api-files-gatsby-browser`

**Comment by noisefilter19** [comment]
Taking up docs/api-files-gatsby-node

**Comment by tanya044** [comment]
docs/api-files-gatsby-node
gonna take this up

**Comment by noisefilter19** [comment]
@tanya044 raised a PR for that yesterday😅

**Comment by noisefilter19** [comment]
Translated docs/api-files-gatsby-ssr.md #56

**Comment by jelonmusk** [comment]
> I'm going to translate docs/gatsby-config
Can i still contribute?

**Comment by mindsers** [comment]
@jelonmusk Thanks for your help! I've updated the list with you name 😉

**Comment by Lavish-Garg** [comment]
i'm going to translate docs/api-specification

**Comment by Lavish-Garg** [comment]
done translating docs/api-specification

**Comment by TechAtVishal** [comment]
tutorial/part-seven #25

**Comment by blacksanta1999** [comment]
I am going to translate docs/recipes/deploying-your-site

**Comment by Lavish-Garg** [comment]
Now I'm going to translate docs/theme-api

**Comment by cedricdelpoux** [comment]
Is Gatsby website in french is published or you wait until every single page is translated? I can't find the url

**Comment by mindsers** [comment]
@cedricdelpoux  It's not published yet. We have to work on it.

**Comment by gauravgupta45** [comment]
Hey, I'm gonna translate `docs/graphql-api`
I think `docs/recipes/deploying-your-site` is already translated but isn't marked above.

**Comment by piraces** [comment]
Hi @tesseralis , do you think labeling this issue with the `hacktoberfest` label would be a good idea? There are many people looking forward to contribute to OSS repositories with that label. In my opinion, it would help to accelerate the process of translation... but it's only a suggestion, not interested in only contributing for the hacktoberfest prize 😀

**Comment by mindsers** [comment]
Hi @piraces! That's actually a good idea. I'll add the badge.

**Comment by rnd-debug** [comment]
Hello. I would like to start the work on `docs/recipes/querying-data`
[Edit] Check this: #63

**Comment by anushkrishnav** [comment]
I want to work on docs/recipes/querying-data or docs/recipes/working-with-images

**Comment by rnd-debug** [comment]
Suggestion: when someone picks up a page, add next to the page name not only the name of the person, but also the date when the item was picked. => easier to visualize if there are any stale traductions.

[Edit] While waiting for #63 to be checked (😉), i am planning to overtake `tutorial/part-seven` (i am aware of the existence of unfinished #25 and of the rejected #62): c'est tjs plus facile de repartir d'un travail commencé.  => translated by #64

**Comment by Marie-Carrere** [comment]
Hi everyone ! 

I just saw that this issue is labeled with the tag `hacktoberfest` but to be eligible to Hacktoberfest, the tag `hacktoberfest` needs to be added on the repository itself or a maintainer has to add the `hacktoberfest-accepted` label on each PR.

My current contribution is not accepted right now by Digital Ocean. 

Could you please update the topic of the repo so our contributions can be eligible to the actual Hacktoberfest ? 

[Classify Your Repository with Topics For Hacktoberfest Video by Digital Ocean](https://www.youtube.com/watch?v=FxBv4FMcDgo&ab_channel=DigitalOcean)

Thank you 
<img width="634" alt="Screenshot 2020-10-12 at 12 33 00" src="https://user-images.githubusercontent.com/30493337/95736851-16f1dd80-0c87-11eb-9189-2378347e43bb.png">

<img width="686" alt="Screenshot 2020-10-12 at 12 18 08" src="https://user-images.githubusercontent.com/30493337/95736742-e6aa3f00-0c86-11eb-81d6-2aff2450bafe.png">


See examples of repositories that have added the topic `hacktoberfest` : 
https://github.com/mui-org/material-ui
https://github.com/django/django
https://github.com/gohugoio/hugo

**Comment by shivroop4444** [comment]
use google translate API

**Comment by Lavish-Garg** [comment]
i will work docs/recipes/working-with-images

**Comment by rnd-debug** [comment]
Up?
Please consider the remark of Marie-Carrere. The end of month is coming 😉

**Comment by mindsers** [comment]
@rnd-debug All merged PRs of this month have the "hacktoberfest-accepted" label. We didn't and won't add the label before the merge stage which is when the maintainers can actually say "this is a valid PR".

**Comment by rnd-debug** [comment]
@mindsers Makes absolutely sense and i agree with this approach. The end of the month is coming though and that was a small reminder about the existing PRs.

**Comment by rnd-debug** [comment]
I am going to pick up `docs/gatsby-link`.
Btw. @ maintainers: can you update the list of TODO items? 
[Edit] check this: https://github.com/gatsbyjs/gatsby-fr/pull/69

**Comment by tithi1march** [comment]
I will begin translating this page docs/recipes/working-with-images, 
Maintainers could you please update the todo list and assign me to the task!

**Comment by Anmol368** [comment]
Translate docs/graphql-api.md #61

**Comment by akashamin01** [comment]
docs/recipes/working-with-images taking this up

**Comment by akashamin01** [comment]
docs/theme-api
 docs/gatsby-link
 docs/gatsby-image

could you please assign me all three of these to contribute

**Comment by rnd-debug** [comment]
@akashamin01 There is already a PR for docs/gatsby-link. 
@mindsers @SamuelAlev @dantereve @gatarelib @alexislepresle Hi, people. Happy end of year celebrations. How about offering to the community a huge Christmas gift by reviewing the pending PRs?

**Comment by akashamin01** [comment]
@rnd-debug  I didn't see anyone assigned to docs/gatsby-link so took it up, But no issues you can go ahead with it.

**Comment by mindsers** [comment]
@akashamin01 Hi! Thanks for your enthusiasm but we prefer that you take files one by one. When you're done w/ one file and created the PR, you can take another one. That way more people can contribute. 😉

**Comment by mindsers** [comment]
@rnd-debug I'm not all for Christmas gift but your PR will be reviewed. No worries. Keep in mind that open source maintainer is not (for most of us) a full-time paid job. We're doing it on our free time and we're doing our best to review all your awesome work.

**Comment by akashamin01** [comment]
@mindsers  I have Given PR for docs/theme-api 
https://github.com/gatsbyjs/gatsby-fr/pull/75

**Comment by akashpatel1310** [comment]
@mindsers can I take this up?
docs/gatsby-image

**Comment by BrookTheBook** [comment]
You could just try to use google translate.

**Comment by rnd-debug** [comment]
> You could just try to use google translate.

@BrookTheBook @shivroop4444 You can probably use the [Merck Manual of Diagnosis](https://en.wikipedia.org/wiki/Merck_Manual_of_Diagnosis_and_Therapy) to perform open-heart surgery. With probably some success. Though, I wouldn't do it.

**Comment by mindsers** [comment]
@BrookTheBook Hi, thanks for the suggestion but every PR that looks like translated by Google Translate was, is and will be rejected.

**Comment by jelonmusk** [comment]
Hi,
is docs/gatsby-config still available for translation?
If yes, then I would like to continue with it.

**Comment by mindsers** [comment]
@jelonmusk It is marked as yours and no PR has been created. So, go ahead 😉

**Comment by Vishal-Sony** [comment]
Hi,
is docs/schema-customization still available for translation?

**Comment by mindsers** [comment]
> Hi,
> is docs/schema-customization still available for translation?

Yes it is

**Comment by Vishal-Sony** [comment]
> 
> 
> > Hi,
> > is docs/schema-customization still available for translation?
> 
> Yes it is

Mark it as mine please .

**Comment by geetujindal7** [comment]
use google translate API

**Comment by rnd-debug** [comment]
Hi,
I see that **contributing/community-contributions** is still not translated and there is no open MR on it (coucou @prateekpardeshi ;) ) => therefore I am taking it. #hacktoberfest 
See here: #80 

Also:
I haven't seen any recent work on  **docs/recipes/pages-layouts**, therefore taking it as well.
See there: #81

**Comment by rnd-debug** [comment]
Btw: concerning Hackoberfest topic:
excerpt from https://hacktoberfest.digitalocean.com/faq
![image](https://user-images.githubusercontent.com/58293036/135747531-1c70a77c-27d6-4d07-8dd6-7864881f0d58.png)

**Comment by harsha14gupta** [comment]
Hello, I'd like to translate `/docs/glossary/build.md`
